// Pre-merge test gate (t_897cca56): no red code reaches the base branch. Contract per
// t_12a92368 (epic t_ee2721f7 16:08Z + 16:15Z amendment) — gateMerge is SYNC:
//   gateMerge(t, opts)  t = {id, worktreePath, worktreeBranch}. Per-root cross-process lock ->
//                       merge the base into the task branch in its worktree -> run the tests ->
//                       land on the base with --no-ff only if green (CAS: if the base moved
//                       meanwhile, re-absorb and re-test; the tested tree IS the merged tree).
//                       opts.runTests({worktreePath, root, base, branch}) sync callback ->
//                       {ok, output}; or opts.testCmd (shell command, cwd = the worktree);
//                       absent -> the real unit suite (`npm test`, node --test) with dependency
//                       sharing and a flaky rerun-once policy.
//   returns {merged:true, base, branch, sha, gate:{state, tests, flaky, tree}}
//         | {merged:false, reason:'tests-failed', output, names}
//         | {merged:false, reason:'master-red', output, names, baseSha}
//         | {merged:false, reason:'infra', output}
//         | {merged:false, refused:true, dirty}
//   git conflicts throw /failed, aborted/ — same contract as worktreeMerge.
const { spawnSync, execFileSync } = require('child_process');
const fs = require('fs');
const os = require('os');
const path = require('path');
const WT = require('./worktree');

const GATE = { TEST_TIMEOUT_MS: Number(process.env.AGENTS_SQUAD_GATE_TEST_TIMEOUT_MS) || 8 * 60_000, INSTALL_TIMEOUT_MS: 5 * 60_000, RERUN_ONCE: true, LOCK_STALE_MS: 25 * 60_000, LOCK_STEAL_MS: 60_000, MAX_CAS_ROUNDS: 3, TAIL_CAP: 1200, MAX_NAMES: 12, MAX_BLOCKS: 5 };
const sleepSync = (ms) => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms);
const gitRun = (cwd, args) => execFileSync('git', args, { cwd, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
const revParse = (root, ref) => gitRun(root, ['rev-parse', ref]);
const errText = (e) => String(e.stderr || e.message || e).trim();
const readIf = (f) => { try { return fs.readFileSync(f, 'utf8'); } catch { return null; } };
const capTail = (out) => String(out || '').slice(-GATE.TAIL_CAP).trim();
const repoRootOf = (t) => path.resolve(t.worktreePath, '..', '..', '..');
const baseBranchOf = (root) => gitRun(root, ['symbolic-ref', '--short', 'HEAD']);
const suiteDirOf = (checkout) => { const p = path.join(checkout, 'app'); return readIf(path.join(p, 'package.json')) != null ? p : (readIf(path.join(checkout, 'package.json')) != null ? checkout : null); };
const healthFile = (root) => path.join(root, '.squad', 'merge-gate.json');
function readHealth(root) { try { return JSON.parse(fs.readFileSync(healthFile(root), 'utf8')); } catch { return { state: 'unknown' }; } }
function writeHealth(root, h) { const f = healthFile(root); fs.mkdirSync(path.dirname(f), { recursive: true }); const tmp = f + '.' + process.pid + '.tmp'; fs.writeFileSync(tmp, JSON.stringify(h, null, 2) + '\n'); fs.renameSync(tmp, f); }
const openTask = (store, id) => { const t = id && store.getTask(id); return t && !['done', 'merge_conflict'].includes(t.status) ? t : null; };
const redMasterTask = (store) => store.listTasks().find((x) => x.redMaster && !['done', 'merge_conflict'].includes(x.status));
const ownerSentence = (h, info) => info.lastMergedTask ? (info.source === 'merge gate' ? `last merged task ${info.lastMergedTask} (${info.lastMergedBranch || '?'})` : `no merge involved — likely a direct commit; last merged task was ${info.lastMergedTask} (owner is a guess)`) : h.lastMergedTask ? `no merge involved — likely a direct commit; last merged task was ${h.lastMergedTask} (owner is a guess)` : 'no merge involved — owner unknown';

function ensureRedMasterTask(store, info = {}) {
  const root = info.root || (() => { const t = store.listTasks().find((x) => x.worktreePath); return t && repoRootOf(t); })();
  if (!root) throw new Error('ensureRedMasterTask: no repo root');
  const prev = readHealth(root); const names = (info.tests || []).slice(0, GATE.MAX_NAMES); const h = { ...prev, state: 'red', failing: names, testOutput: capTail(info.output), base: info.base || prev.base, updatedAt: new Date().toISOString() };
  const wasRed = prev.state === 'red'; if (!wasRed) h.sinceMs = Date.now();
  if (info.lastMergedTask) { h.lastMergedTask = info.lastMergedTask; h.lastMergedBranch = info.lastMergedBranch || null; }
  let p0 = redMasterTask(store) || openTask(store, prev.p0TaskId);
  if (!p0) { p0 = store.createTask({ title: `Fix red master: ${h.base || 'base branch'} unit tests failing`, description: `Auto-created by the merge gate: the base branch fails the unit suite.\nFailing: ${names.join(', ') || 'unknown failures'}\n${ownerSentence(prev, info)}${info.detail ? `\nSource: ${info.detail}` : ''}`, priority: 'P0', createdBy: 'merge-gate' }); store.updateTask(p0.id, { redMaster: true }); }
  h.p0TaskId = p0.id; writeHealth(root, h);
  if (!wasRed) store.appendLog({ at: Date.now(), nodeId: null, kind: 'master.red', text: `master is red: ${names.join(', ') || 'unknown failures'}. ${ownerSentence(prev, info)}.` });
  return p0;
}
function markMasterGreen(store, info = {}) {
  const root = info.root; if (!root) throw new Error('markMasterGreen: root required');
  const prev = readHealth(root); const wasRed = prev.state === 'red'; const h = { ...prev, state: 'green', failing: [], testOutput: null, lastGreenTree: info.tree || prev.lastGreenTree, base: info.base || prev.base, updatedAt: new Date().toISOString() }; if (info.lastMergedTask) { h.lastMergedTask = info.lastMergedTask; h.lastMergedBranch = info.lastMergedBranch || null; }
  writeHealth(root, h);
  if (wasRed) { store.appendLog({ at: Date.now(), nodeId: null, kind: 'master.green', text: `master is green again (verified by the merge gate${info.source ? ' — ' + info.source : ''}).` }); let p0 = redMasterTask(store) || openTask(store, prev.p0TaskId); if (p0) { if (p0.status === 'todo' && !p0.assignee) { store.commentTask(p0.id, 'system', 'master verified green by the merge gate — auto-closing this fix task.'); store.updateTask(p0.id, { status: 'done' }); } else store.commentTask(p0.id, 'system', 'master verified green by the merge gate — if your fix is already in, close this task.'); } h.p0TaskId = null; writeHealth(root, h); }
  return h;
}
function recordGateBlock(store, info = {}) { if (!info.root) return; const h = readHealth(info.root); const blocks = [{ taskId: info.taskId, tests: (info.tests || []).slice(0, GATE.MAX_NAMES), at: Date.now() }, ...(h.gateBlocks || [])].slice(0, GATE.MAX_BLOCKS); writeHealth(info.root, { ...h, gateBlocks: blocks, updatedAt: new Date().toISOString() }); }
function redMasterSnapshot(store) { if (!store || typeof store.listTasks !== "function") return null; const xs = store.listTasks().filter((x) => x.worktreePath); if (!xs.length) return null; let root; try { root = repoRootOf(xs[xs.length - 1]); } catch { return null; } const h = readHealth(root); return { red: h.state === 'red', since: h.sinceMs || null, failingTests: h.state === 'red' ? (h.failing || []) : [], testOutput: h.state === 'red' ? (h.testOutput || null) : null, fixTaskId: h.state === 'red' ? (h.p0TaskId || null) : null, lastMergedTaskId: h.lastMergedTask || null, gateBlocks: h.gateBlocks || [] }; }

function withMergeLock(root, fn) {
  const lock = path.join(root, '.squad', 'merge.lock'); fs.mkdirSync(path.dirname(lock), { recursive: true }); const acquire = () => { fs.mkdirSync(lock); fs.writeFileSync(path.join(lock, 'pid'), String(process.pid)); }; const deadline = Date.now() + GATE.LOCK_STALE_MS;
  for (;;) { try { acquire(); break; } catch (e) { if (e.code !== 'EEXIST') throw e; let age = 0; try { age = Date.now() - fs.statSync(lock).mtimeMs; } catch {} if (age > GATE.LOCK_STEAL_MS || Date.now() > deadline) { try { fs.rmSync(lock, { recursive: true, force: true }); } catch {} continue; } sleepSync(50); } }
  try { return fn(); } finally { try { fs.rmSync(lock, { recursive: true, force: true }); } catch {} }
}
function childEnv() { const e = { ...process.env, CI: '1' }; for (const k of Object.keys(e)) if ((k.startsWith('AGENTS_SQUAD_') && k !== 'AGENTS_SQUAD_GATE_TEST_TIMEOUT_MS') || k === 'NODE_TEST_CONTEXT') delete e[k]; return e; }
function parseSummary(out) { const tests = Number((out.match(/^[^\S\n]*ℹ tests (\d+)/m) || [])[1]); const fail = Number((out.match(/^[^\S\n]*ℹ fail (\d+)/m) || [])[1]); const names = [...new Set((out.match(/^✖ (?!failing tests:)(.+)$/gm) || []).map((l) => l.replace(/^✖ /, '').replace(/\s+\([\d.]+ms\)$/, '').trim().slice(0, 140)))].filter((n) => !/^\d+\.\s/.test(n)); return { summarySeen: Number.isFinite(tests), tests: tests || 0, fail: Number.isFinite(fail) ? fail : 0, names: names.slice(0, GATE.MAX_NAMES) }; }
function isInfra(out, timedOut) { if (timedOut) return true; const s = parseSummary(out); if (!s.summarySeen) return true; const bare = /Cannot find module '([^']+)'/g; let m; while ((m = bare.exec(out))) if (!m[1].startsWith('.') && !m[1].startsWith('/')) return true; return false; }
function ensureDeps(wtPkg, rootPkg) { try { fs.lstatSync(path.join(wtPkg, 'node_modules')); return null; } catch {} const same = readIf(path.join(wtPkg, 'package.json')) === readIf(path.join(rootPkg, 'package.json')) && readIf(path.join(wtPkg, 'package-lock.json')) === readIf(path.join(rootPkg, 'package-lock.json')); if (same && fs.existsSync(path.join(rootPkg, 'node_modules'))) { try { fs.symlinkSync(path.join(rootPkg, 'node_modules'), path.join(wtPkg, 'node_modules'), 'dir'); return null; } catch {} } const r = spawnSync('npm', ['install', '--no-save', '--no-audit', '--no-fund', '--loglevel=error'], { cwd: wtPkg, env: childEnv(), timeout: GATE.INSTALL_TIMEOUT_MS, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); const out = `${r.stdout || ''}${r.stderr || ''}`; return r.error || r.status !== 0 ? `npm install failed in the worktree (${capTail(out) || (r.error && r.error.message) || 'no output'})` : null; }
function runDefaultSuite(wtPkg, rootPkg) { const depErr = ensureDeps(wtPkg, rootPkg); if (depErr) return { state: 'infra', names: [], output: depErr, tests: 0, flaky: [] }; let first = null; for (let attempt = 0; attempt < (GATE.RERUN_ONCE ? 2 : 1); attempt++) { const r = spawnSync('npm', ['test'], { cwd: wtPkg, env: childEnv(), timeout: GATE.TEST_TIMEOUT_MS, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); const out = `${r.stdout || ''}${r.stderr || ''}`; if (isInfra(out, !!r.error || r.signal === 'SIGTERM' || r.signal === 'SIGKILL')) { const timed = !r.error && (r.signal === 'SIGTERM' || r.signal === 'SIGKILL'); if (attempt === 0 && !timed) continue; return { state: 'infra', names: [], output: timed ? `unit suite timed out after ${Math.round(GATE.TEST_TIMEOUT_MS / 1000)}s` : capTail(out), tests: 0, flaky: [] }; } const s = parseSummary(out); if (s.fail === 0 && r.status === 0) return { state: 'green', names: [], output: '', tests: s.tests, flaky: first ? first.names : [] }; first = { ...s, output: capTail(out) }; } return { state: 'red', names: first.names, output: first.output, tests: first.tests, flaky: [] }; }
function runSuiteOnBase(root, baseSha) { const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'squad-gate-base-')); try { gitRun(root, ['worktree', 'add', '--detach', dir, baseSha]); const pkg = suiteDirOf(dir); return pkg ? runDefaultSuite(pkg, suiteDirOf(root) || pkg) : { state: 'skipped', names: [], output: '' }; } catch (e) { return { state: 'infra', names: [], output: 'base sanity check failed: ' + errText(e) }; } finally { try { gitRun(root, ['worktree', 'remove', '--force', dir]); } catch { try { fs.rmSync(dir, { recursive: true, force: true }); } catch {} } } }
function runGateTests(t, root, base, opts) { const ctx = { worktreePath: t.worktreePath, root, base, branch: t.worktreeBranch }; if (opts.runTests) { let r; try { r = opts.runTests(ctx) || {}; } catch (e) { r = { ok: false, output: 'runTests threw: ' + errText(e) }; } const s = parseSummary(String(r.output || '')); return { state: r.ok ? 'green' : 'red', names: s.names, output: capTail(r.output), tests: 0, flaky: [], defaultRunner: false }; } if (opts.testCmd) { const r = spawnSync('/bin/sh', ['-c', String(opts.testCmd)], { cwd: t.worktreePath, env: childEnv(), timeout: GATE.TEST_TIMEOUT_MS, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] }); const out = `${r.stdout || ''}${r.stderr || ''}`; const s = parseSummary(out); return { state: !r.error && r.status === 0 ? 'green' : 'red', names: s.names, output: capTail(out), tests: 0, flaky: [], defaultRunner: false }; } const pkg = suiteDirOf(t.worktreePath); return pkg ? { ...runDefaultSuite(pkg, suiteDirOf(root) || pkg), defaultRunner: true } : { state: 'skipped', names: [], output: '', tests: 0, flaky: [], defaultRunner: true }; }
function gateMerge(t, opts = {}) { const root = repoRootOf(t); const base = baseBranchOf(root); return withMergeLock(root, () => { for (let round = 0; round < GATE.MAX_CAS_ROUNDS; round++) { let ahead; try { ahead = Number(gitRun(root, ['rev-list', '--count', `${base}..${t.worktreeBranch}`])); } catch { ahead = 1; } if (ahead === 0) return { base, branch: t.worktreeBranch, root, merged: false, gate: { state: 'skipped', note: 'no commits ahead' } }; const dirty = WT.dirtyMainFiles(root); if (dirty.length) return { base, branch: t.worktreeBranch, root, merged: false, refused: true, dirty }; const testedBase = revParse(root, base); try { gitRun(t.worktreePath, ['merge', '--no-edit', base]); } catch (e) { try { gitRun(t.worktreePath, ['merge', '--abort']); } catch {} throw new Error(`merge of ${t.worktreeBranch} into ${base} failed, aborted: ${errText(e)}`); } const g = runGateTests(t, root, base, opts); if (g.state === 'green' || g.state === 'skipped') { if (revParse(root, base) !== testedBase) continue; try { gitRun(root, ['merge', '--no-ff', '--no-edit', t.worktreeBranch]); } catch (e) { try { gitRun(root, ['merge', '--abort']); } catch {} throw new Error(`landing ${t.worktreeBranch} into ${base} failed, aborted: ${errText(e)}`); } const mergedTree = revParse(root, `${base}^{tree}`); const testedTree = revParse(t.worktreePath, 'HEAD^{tree}'); if (mergedTree !== testedTree) return { base, branch: t.worktreeBranch, root, merged: true, reason: 'tree-mismatch', gate: { state: 'tree-mismatch' } }; return { base, branch: t.worktreeBranch, root, merged: true, sha: revParse(root, base), gate: { state: g.state, tests: g.tests || 0, flaky: g.flaky || [], tree: mergedTree } }; } if (g.state === 'red') { if (g.defaultRunner) { const baseCheck = runSuiteOnBase(root, testedBase); if (baseCheck.state === 'red') return { base, branch: t.worktreeBranch, root, merged: false, reason: 'master-red', names: baseCheck.names, output: baseCheck.output, baseSha: testedBase, gate: { state: 'master-red' } }; } return { base, branch: t.worktreeBranch, root, merged: false, reason: 'tests-failed', names: g.names, output: g.output, baseSha: testedBase, gate: { state: 'red' } }; } return { base, branch: t.worktreeBranch, root, merged: false, reason: 'infra', output: g.output, names: [], gate: { state: 'infra' } }; } throw new Error(`merge gate: base branch ${base} kept moving under concurrent merges; no merge performed after ${GATE.MAX_CAS_ROUNDS} rounds`); }); }
function checkMasterHealth(store) { const xs = store.listTasks().filter((x) => x.worktreePath); if (!xs.length) return; let root, base; try { root = repoRootOf(xs[xs.length - 1]); base = baseBranchOf(root); } catch { return; } const h = readHealth(root); let tree; try { tree = revParse(root, `${base}^{tree}`); } catch { return; } if (h.state === 'green' && h.lastGreenTree === tree) return; withMergeLock(root, () => { const r = runSuiteOnBase(root, tree); if (r.state === 'red') ensureRedMasterTask(store, { root, tests: r.names, output: r.output, base, source: 'startup check' }); else if (r.state === 'green') markMasterGreen(store, { root, tree, base, source: 'startup check' }); }); }
module.exports = { GATE, gateMerge, checkMasterHealth, ensureRedMasterTask, markMasterGreen, recordGateBlock, redMasterSnapshot, parseSummary, isInfra, runDefaultSuite, withMergeLock, readHealth, suiteDirOf, ensureDeps, runSuiteOnBase };
